const colors = {
  light: {
    text: "#0f172a",
    tint: "#4f6ef7",
    background: "#f7f8fa",
    foreground: "#0f172a",
    card: "#ffffff",
    cardForeground: "#0f172a",
    primary: "#4f6ef7",
    primaryForeground: "#f8fafc",
    secondary: "#f0f4f8",
    secondaryForeground: "#0f172a",
    muted: "#f0f4f8",
    mutedForeground: "#6b7fa3",
    accent: "#eef1fe",
    accentForeground: "#4f6ef7",
    destructive: "#f03e3e",
    destructiveForeground: "#ffffff",
    success: "#22c55e",
    successForeground: "#ffffff",
    warning: "#f59e0b",
    warningForeground: "#ffffff",
    border: "#e0e7ef",
    input: "#e0e7ef",
    priorityLow: "#6b7280",
    priorityMedium: "#3b82f6",
    priorityHigh: "#f97316",
    priorityCritical: "#ef4444",
  },
  dark: {
    text: "#f8fafc",
    tint: "#6b7eff",
    background: "#0f172a",
    foreground: "#f8fafc",
    card: "#1a2540",
    cardForeground: "#f8fafc",
    primary: "#6b7eff",
    primaryForeground: "#f8fafc",
    secondary: "#1e2d47",
    secondaryForeground: "#f8fafc",
    muted: "#1e2d47",
    mutedForeground: "#8fa3c0",
    accent: "#1e2d47",
    accentForeground: "#6b7eff",
    destructive: "#f03e3e",
    destructiveForeground: "#ffffff",
    success: "#22c55e",
    successForeground: "#ffffff",
    warning: "#f59e0b",
    warningForeground: "#ffffff",
    border: "#1e2d47",
    input: "#1e2d47",
    priorityLow: "#9ca3af",
    priorityMedium: "#60a5fa",
    priorityHigh: "#fb923c",
    priorityCritical: "#f87171",
  },
  radius: 12,
};

export default colors;
